#pragma once

#include <Windows.h>

enum class ConsoleColor : WORD
{
	Black = 0,
	Blue = FOREGROUND_BLUE,
	Green = FOREGROUND_GREEN,
	Red = FOREGROUND_RED,
	Cyan = FOREGROUND_BLUE | FOREGROUND_GREEN,
	Magenta = FOREGROUND_RED | FOREGROUND_BLUE,
	Yellow = FOREGROUND_RED | FOREGROUND_GREEN,
	White = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
	BrightBlue = FOREGROUND_BLUE | FOREGROUND_INTENSITY,
	BrightGreen = FOREGROUND_GREEN | FOREGROUND_INTENSITY,
	BrightRed = FOREGROUND_RED | FOREGROUND_INTENSITY,
	BrightCyan = FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY,
	BrightMagenta = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY,
	BrightYellow = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY,
	BrightWhite = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY
};
